id: PE645854C
initial_creation_type: input
source_metadata:
  Title: ''
  Editor: Shastri, Svami Dwarikadas
  Publisher: Bauddha Bharati
  Place of Publication: India
  Year: '1994'
  Nyāyabindu prakaraṇakārikā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:49:01.366716'
last_modified_at: '2022-03-08T16:49:01.366725'
